import { createAction } from '@reduxjs/toolkit';
import { ActionType } from '../types/actions';
import {CommentsCount, CommentType, GuitarType} from '../types/data';

export const loadAllGuitars = createAction<GuitarType[]>(ActionType.LoadAllGuitars);
export const loadGuitars = createAction<GuitarType[]>(ActionType.LoadGuitars);
export const setIsGuitarsLoaded = createAction<boolean>(ActionType.SetIsGuitarsLoaded);
export const loadProductInfo = createAction<GuitarType>(ActionType.LoadProductInfo);
export const setIsGuitarLoaded = createAction<boolean>(ActionType.SetIsGuitarLoaded);
export const loadTotalCount = createAction<number>(ActionType.LoadTotalCount);
export const loadCommentsCount = createAction<CommentsCount>(ActionType.LoadCommentsCount);
export const loadComments = createAction<CommentType[]>(ActionType.LoadComments);
export const setCurrentPage = createAction<number>(ActionType.SetCurrentPage);
export const setMinPrice = createAction<string>(ActionType.SetMinPrice);
export const setMaxPrice = createAction<string>(ActionType.SetMaxPrice);
export const setMinPricePlaceholder = createAction<number>(ActionType.SetMinPricePlaceholder);
export const setMaxPricePlaceholder = createAction<number>(ActionType.SetMaxPricePlaceholder);
export const setSortType = createAction<string>(ActionType.SetSortType);
export const setSortOrder = createAction<string>(ActionType.SetSortOrder);
export const setGuitarTypes = createAction<(string | null)[]>(ActionType.SetGuitarTypes);
export const setStringsCounts = createAction<(string | null)[]>(ActionType.SetStringsCounts);
export const setProductTab = createAction<string>(ActionType.SetProductTab);
